const handleError = (err, req, res, next) => {
    console.log(res, err)
}

module.exports = handleError;